[build]
builder = "dockerfile"

[deploy]
startCommand = "./start-railway.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
# Laravel Temel Ayarları
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://your-app-name.railway.app"
APP_NAME = "Gaffini"
APP_KEY = ""
LOG_CHANNEL = "stack"
LOG_LEVEL = "error"

# Veritabanı Ayarları (Railway otomatik sağlar)
DB_CONNECTION = "mysql"
DB_HOST = "${MYSQLHOST}"
DB_PORT = "${MYSQLPORT}"
DB_DATABASE = "${MYSQLDATABASE}"
DB_USERNAME = "${MYSQLUSER}"
DB_PASSWORD = "${MYSQLPASSWORD}"
DB_CHARSET = "utf8mb4"
DB_COLLATION = "utf8mb4_unicode_ci"

# Cache ve Session Ayarları
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"
QUEUE_CONNECTION = "sync"

# Mail ve Broadcasting
BROADCAST_DRIVER = "log"
MAIL_MAILER = "log"

# File System
FILESYSTEM_DISK = "local"

# Security
SESSION_SECURE_COOKIE = "true"
SESSION_SAME_SITE = "lax"

# Performance
OPCACHE_ENABLE = "1"
OPCACHE_MEMORY_CONSUMPTION = "128"
OPCACHE_MAX_ACCELERATED_FILES = "4000"

[deploy.postDeploy]
commands = [
    "php artisan key:generate --force",
    "php artisan migrate --force",
    "php artisan storage:link --force",
    "php artisan config:clear",
    "php artisan cache:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]
