[build]
builder = "dockerfile"

[deploy]
startCommand = "/start-railway.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.variables]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://your-app-name.railway.app"
LOG_CHANNEL = "stack"
LOG_LEVEL = "error"
DB_CONNECTION = "mysql"
DB_HOST = "${MYSQLHOST}"
DB_PORT = "${MYSQLPORT}"
DB_DATABASE = "${MYSQLDATABASE}"
DB_USERNAME = "${MYSQLUSER}"
DB_PASSWORD = "${MYSQLPASSWORD}"
CACHE_DRIVER = "file"
SESSION_DRIVER = "file"
QUEUE_CONNECTION = "sync"
BROADCAST_DRIVER = "log"
FILESYSTEM_DISK = "local"
